language: elixir
elixir:
  - 1.1.0
otp_release:
  - 17.4
addons:
  postgresql: "9.4"
sudo: false # to use faster container based build environment
env:
  - ELIXIR_ERL_OPTIONS=""
  - ELIXIR_ERL_OPTIONS="+T 9"
script:
  - mix deps.get
  - mix test
